name: Generar galeria

on:
  push:
    paths:
      - 'svg/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generar HTML
        run: node generate.js

      - name: Commit cambios
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "update gallery" || echo "no changes"
          git push
